services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
  frontend:
    build: ./frontend
    ports:
      - "80:80"
  prometheus:
    image: prom/prometheus
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"