- name: Setup Minikube DevOps Node
  hosts: devops_node
  become: yes
  roles:
    - { role: docker, tags: ['docker'] }
    - { role: kubectl, tags: ['kubectl', 'k8s_deploy', 'k8s_setup'] }
    - { role: minikube, tags: ['minikube', 'k8s_deploy', 'k8s_setup'] }
    - { role: k8s_deploy, tags: ['k8s_deploy'] }
    - { role: prometheus, tags: ['prometheus'] }
