- name: Create app folder to store deployment files
  file:
    path: /home/ubuntu/app
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'

- name: Copy Kubernetes deployment files
  copy:
    src: ../../../../../k8s/
    dest: /home/ubuntu/app/
    owner: ubuntu
    group: ubuntu
    mode: '0644'

- name: Wait for Kubernetes API to be ready
  shell: |
    for i in {1..10}; do
      if KUBECONFIG=/home/ubuntu/.kube/config kubectl version --short; then
        echo "API is ready!"
        exit 0
      fi
      echo "Waiting for Kubernetes API..."
      sleep 10
    done
    echo "Kubernetes API not ready after waiting!"
    exit 1
  changed_when: false

- name: Apply Backend Deployment
  shell: KUBECONFIG=/home/ubuntu/.kube/config kubectl apply -f /home/ubuntu/app/backend-deployment.yaml
  args:
    executable: /bin/bash

- name: Apply Frontend Deployment
  shell: KUBECONFIG=/home/ubuntu/.kube/config kubectl apply -f /home/ubuntu/app/frontend-deployment.yaml
  args:
    executable: /bin/bash

- name: Apply Service Config
  shell: KUBECONFIG=/home/ubuntu/.kube/config kubectl apply -f /home/ubuntu/app/service.yaml
  args:
    executable: /bin/bash

- name: Verify pods are running
  shell: KUBECONFIG=/home/ubuntu/.kube/config kubectl get pods -o wide
  register: pod_output
  changed_when: false

- name: Show pods
  debug:
    var: pod_output.stdout


